### ISSUE TITLE
HeroMasteryTier Hero Encoding

### ISSUE THREAD

**Issue by MGatner** [Blizzard/heroprotocol#77] opened 2018-12-26 11:35 UTC
In initdata the hero mastery array, m_hero is listed as a four character code, but the values are coming through garbled (even with non-ASCII escaped characters, like \x13). I’m not sure how heroprotocol is attempting to encode the string, but Barrett solves this with the following:
https://github.com/barrett777/Heroes.ReplayParser/blob/3e461251ccf36d0aaad71daba2b4223e61c455b6/Heroes.ReplayParser/MPQFiles/ReplayInitData.cs#L305

Output should be the four-character “attribute_id” hero identifier.

**Comment by MGatner** [comment] 2018-12-27 19:21
Losing my mind here. Just to triple reconfirm the issue I just posted, I returned the bits directly using "{0:b}".format(bits), first by the four 8-bit chunks:
1001000 10011 1010000 10010001

And next as one 32-bit chunk:
1001000010000010100111001000001

In other words - exactly as I was already seeing. There's definitely something happening at the bit reader or file formate level that I'm no understanding 'cause this is straight up screwball.

FWIW an easy workaround is to modify read_unaligned_bytes in decoders.py (line 83) to read 32-bits at once, then unpack that into its byte representation and read those as characters one at a time. I'm still at a loss how to convert the current output into anything usable.

**Comment by healingbrew** [comment] 2018-12-28 00:34
for curiousity's sake, what happens if you change `read_unaligned_bytes` to

```python
def read_unaligned_bytes(self, bytes):
  bits = self.read_bits(8 * bytes)
  return ''.join([chr(bits[i:i+8]) for i in xrange(0, 8 * bytes, 8)])
```

**Comment by MGatner** [comment] 2018-12-28 14:20
@healingbrew TypeError: 'int' object has no attribute '__getitem__'

**Comment by barrett777** [comment] 2018-12-28 18:06
I think the issue is that after reading the first 8-bit chunk, the reader aligns itself to the next byte, skipping over some bits

You can see what I experienced in C# here: https://repl.it/repls/CloudyGrimPascal

**Comment by Agilhardt** [comment] 2020-04-20 19:25
Fixed in the next update.

**Closed by Agilhardt** 2020-04-20 19:25 UTC
Labels: bug

**Comment by MGatner** [comment] 2020-05-12 14:43
@Agilhardt It appears that `2.50.1.79515` did not affect **heroprotocol.py** - did this fix get bumped?

**Comment by Agilhardt** [comment] 2020-05-12 15:46
The fix is in `decoders.py` in fa99bf2. To test, parse a replay with `--details` and check `m_lobbyState.m_slots[0].m_heroMasteryTiers`.

Please let me know if it's not working elsewhere.
